meta_data:
  pipeline_exp_name: 'r2cnn'
  description: "the complete pipeline of world model"
  num_workers: 1
  use_gpu: true
  log: true
  wandb: true
  key_config:
    common:
      model_fn: 'model_fn'
    algo_training:



common:
  dataset_root: "../dataset"
  model_fn: "png2npz" # "resnet50", "resnet101", "densenet161", "sketchanet"
  num_workers: 32

algo_training:
  variables:
    seed: [ 0 ] # seed is needed

  constants:
    exp_name: "png2npz"  # exp_name is required
    script_path: scripts.png2npz
    batch_size: 48
    imgsize: 224
    learn_rate_step: -1
    thickness: 1.0




















