meta_data:
  pipeline_exp_name: 'r2cnn'
  description: "the complete pipeline of world model"
  num_workers: 1
  use_gpu: true
  log: true
  wandb: false
  key_config:
    common:
      model_fn: 'model_fn'
    algo_training:



common:
  dataset_root: "../dataset"
  model_fn: "resnet50" # "resnet50", "resnet101", "densenet161", "sketchanet"

algo_training:
  variables:
    learn_rate: [ 1.0e-4 ]
    seed: [ 0 ]

  constants:
    exp_name: "r2cnn_resnet50"  # exp_name is required
    script_path: scripts.r2cnn
    batch_size: 48
    imgsize: 28
    learn_rate_step: -1
    num_epochs: 5
    report_scalar_freq: 100
    thickness: 1.0
    valid_freq: 1
    weight_decay: -1
    dropout: 0.5
    intensity_channels: 8





















