meta_data:
  pipeline_exp_name: 'r2cnn'
  description: "the complete pipeline of world model"
  num_workers: 1
  use_gpu: true
  log: true
  wandb: false
  key_config:
    common:
      model_fn: 'model_fn'
    algo_training:



common:
  dataset_root: "../dataset"
  model_fn: "vit" # "resnet50", "resnet101", "densenet161", "sketchanet", swintransformer

algo_training:
  variables:
    learn_rate: [ 5.0e-5 ]
    seed: [ 0 ]

  constants:
    exp_name: "vit_r2cnn2"  # exp_name is required
    script_path: scripts.r2cnn
    batch_size: 128
    imgsize: 28
    learn_rate_step: 1
    num_epochs: 5
    report_scalar_freq: 100
    thickness: 0.5
    valid_freq: 1
    weight_decay: 0.05
    patch_size: 1
    embed_dim: 48
    dropout: 0.5
    intensity_channels: 8




















